### ISSUE TITLE
Fix required object parameters

### ISSUE THREAD

**Issue by wieltar** [Rinkeeee96/FoxTrot_SA_Engine#42]
In particle en object is het heel moeilijk om required variablen af te dwingen omdat particle geen constructor heeft die dit eist
Het is niet makkelijk om te zien wat er nu een must have is en wat optioneel is, idealiter moet dit worden afgdewongen via een constructor

**Comment by ttleeuw** [comment]
Enhancement, geen bug

**Comment by Rinkeeee96** [comment]
Heb hier even naar zitten kijken, maar welke variablen wil je afdwingen op particles? 
Zie hieronder hoe je een particle aanmaakt. 
X en Y maybe? Willen we dat dan ook meteen voor een Object doen?
![image](https://user-images.githubusercontent.com/10192977/98588437-fd66a480-22cb-11eb-95e7-b659298def69.png)
