### ISSUE TITLE
Object position is ignored in particle

### ISSUE THREAD

**Issue by wieltar** [Rinkeeee96/FoxTrot_SA_Engine#43]
De particle position logic staat compleet los van de object position paremeters maar deze zijn wel aan te roepen omdat particle adapter een object is via polymorfisme

Deze wordt zo te zien niet gebruikt in particle of via de adapter/bridge op de juiste manier gezet, dit kan voor verwarring zorgen en moet z.s.m gefixt worden

Verwacht gedrag:
Object en particle delen relevante eigenschappen

**Comment by Rinkeeee96** [comment]
Goeie! Pak ik eind van de week ff op

**Comment by Rinkeeee96** [comment]
Pr is open. Kun jij is kijken of je het er mee eens bent?
[Pull Request](https://github.com/Rinkeeee96/FoxTrot_SA_Engine/pull/66)
