### ISSUE TITLE
Static objects are redrawn every tick

### ISSUE THREAD

**Issue by Maxvani** [Rinkeeee96/FoxTrot_SA_Engine#59]
Statische objecten worden iedere tick opnieuw getekend. Het gaat waarschijnlijk redelijk wat performance opleveren door alle statische objecten maar 1x te tekenen aangezien iedere Tile een apart statisch object wordt.

**Comment by Rinkeeee96** [comment]
Aangezien het scherm elke keer gecleaned wordt moeten ze op dit moment opnieuw getekend worden. 
Ik weet niet of sdl2 de mogelijkheid heeft om bepaalde dingen te "onttekenen" en om ze vervolgens anders anders te tekenen.

**Comment by Rinkeeee96** [comment]
@TheLarsJansen Kan dit anders?

**Comment by wieltar** [comment]
ik weet niet of het erg is, je moet namelijk alles tekenen elk frame en dus elk frame die buffer wordt leeggegooid 
Hier is een github linkje waar ze het hebben over het targeten van specifieke regio's van het scherm die geupdated worden:
https://stackoverflow.com/questions/46311411/rendering-parts-of-the-screen-on-each-frame-with-sdl2

**Comment by wieltar** [comment]
Misschien dat we die lagen als targets kunnen aanmaken en dan zo de "main loop" op een laag targetten die losstaat van de achtergrond / static tiles, dan kan daarin de buffer blijven bestaan en wordt alleen de buffer geleegd van de laag die op dat moment getekend wordt.

zo zou je later altijd nog kunnen kijken naar een parallax achtergrond ofzo
