### ISSUE TITLE
Object has set jump height function, but variable is not used in physics

### ISSUE THREAD

**Issue by Rinkeeee96** [Rinkeeee96/FoxTrot_SA_Engine#60]

**Comment by Rinkeeee96** [comment]
@WilliamRossAvans

**Comment by wieltar** [comment]
Hij wordt aangeroepen in physicsbody.cs op regel 40 volgens mijn find all

**Comment by WilliamRossAvans** [comment]
Ja klopt, dit wordt aangeroepen via player -> physicsengine -> physicsfacade

**Comment by Rinkeeee96** [comment]
Denk dat ik al weet waarom het niet werkte. Aangezien in de constructor van een player de jumpheight al geset wordt
