### ISSUE TITLE
Pull apart object class into their respectable entities e.g movable, drawable etc.

### ISSUE THREAD

**Issue by wieltar** [Rinkeeee96/FoxTrot_SA_Engine#67]
**Pull request details** 
GEEN PULLREQUEST, SUGGESTIE 
veranderingen in bijvoorbeeld de toekomstige versie van de implementatie van de triggers, of de buttons, nog niet over uit.  TBD
 
Het idee is dat de main object class uit elkaar wordt getrokken naar verschillende classes zoals drawable, movable, Particle etc. Hierdoor creeeren we een duidelijke hierarchie en wordt de object class zelf niet zo groot.

Als we gaan werken met objecten die geen sprite nodig hebben of niet hoeven te bewegen hoeven die dan ook geen implementatie te hebben hiervoor die dit mogelijk maakt. Mocht een object drawable en movable zijn in de game dan is een eventuele oplossing multiple inheritance

**Comment by Rinkeeee96** [comment]
Ben ik het mee eens. Object class wordt tegroot voor alles wat we ermee doen. Misschien eerste even komende sprint aankijken wat we allemaal nog moeten doen aan Object en vervolgens een lijstje maken van hoe we hem kunnen opsplitsen?

**Comment by ttleeuw** [comment]
Mee eens, multiple inherentence krijg je echter wel snel al een ECS-achtig systeem weet niet of het de oplossing is

**Comment by Rinkeeee96** [comment]
@ttleeuw Dit bepalen we zelf he in hoevere we dit op ECS gaan laten lijken.

**Comment by WilliamRossAvans** [comment]
Already fixed
